### ISSUE TITLE
declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :jwiki

### ISSUE THREAD

**Issue by nicolas-raoul** [fastily/wpkit#1]
Just after cloning the repo:
```
$ ./gradlew jar

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Project : declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :jwiki.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by Giszmo** [comment]
I get this error with a custom project and googling I find your issue. Any success? Here it complains about a line that works on my laptop but on the server not. The line is:

    jar { from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } } }

**Comment by fastily** [comment]
Until today, I had no idea that anyone besides myself was building my projects!  Unfortunately, the procedure is a bit hacky; I'll try to make it better with future updates.

1) Clone [jwiki](https://github.com/fastily/jwiki).
2) In the same directory, clone ctools.
3) `cd` into `ctools` and run `./gradlew build -x test`
4) Build the jar by running `./gradlew mtc`
5) You can find the jar in `./build/libs`

**Comment by nicolas-raoul** [comment]
That fixed the problem, thanks @fastily !

@Giszmo We probably won't be able to help you, as the solution will not be the same... I suggest you ask at StackOverflow. Cheers!
